using static Sokol.SG;
using static Sokol.SG.sg_backend;
using static Sokol.SG.sg_shader_stage;
using static Sokol.SG.sg_uniform_type;
using static Sokol.SG.sg_uniform_layout;
using static Sokol.SG.sg_image_type;
using static Sokol.SG.sg_sampler_type;
using static Sokol.SG.sg_image_sample_type;
using static Sokol.SG.sg_shader_attr_base_type;
using System.Numerics;
using System.Runtime.InteropServices;


using hmm_vec2=System.Numerics.Vector2;
using hmm_vec3=System.Numerics.Vector3;
using hmm_vec4=System.Numerics.Vector4;
using hmm_mat4=System.Numerics.Matrix4x4;


using vec2_t=System.Numerics.Vector2;
using vec3_t=System.Numerics.Vector3;
using vec4_t=System.Numerics.Vector4;
using mat44_t=System.Numerics.Matrix4x4;


namespace fs_functions_shader_skinning_cs_skinning {

public static unsafe class Shaders 
{
    /*
        #version:1# (machine generated, don't edit!)

        Generated by sokol-shdc (https://github.com/floooh/sokol-tools)

        Cmdline:
            sokol-shdc --input shaders/fs_functions.glsl --defines SKINNING --module skinning --reflection --output shaders/compiled/android/fs_functions-shader-skinning.cs --slang glsl300es -f sokol_csharp

        Overview:
        =========
        Bindings:
    */
}

} // namescape 

