using static Sokol.SG;
using static Sokol.SG.sg_backend;
using static Sokol.SG.sg_shader_stage;
using static Sokol.SG.sg_uniform_type;
using static Sokol.SG.sg_uniform_layout;
using static Sokol.SG.sg_image_type;
using static Sokol.SG.sg_sampler_type;
using static Sokol.SG.sg_image_sample_type;
using static Sokol.SG.sg_shader_attr_base_type;
using System.Numerics;
using System.Runtime.InteropServices;


using hmm_vec2=System.Numerics.Vector2;
using hmm_vec3=System.Numerics.Vector3;
using hmm_vec4=System.Numerics.Vector4;
using hmm_mat4=System.Numerics.Matrix4x4;


using vec2_t=System.Numerics.Vector2;
using vec3_t=System.Numerics.Vector3;
using vec4_t=System.Numerics.Vector4;
using mat44_t=System.Numerics.Matrix4x4;


namespace phong_shader_cs {

public static unsafe class Shaders 
{
    /*
        #version:1# (machine generated, don't edit!)

        Generated by sokol-shdc (https://github.com/floooh/sokol-tools)

        Cmdline:
            sokol-shdc --input shaders/phong.glsl --output shaders/compiled/osx/phong-shader.cs --slang metal_macos -f sokol_csharp

        Overview:
        =========
        Shader program: 'phong':
            Get shader desc: phong_shader_desc(sg_query_backend());
            Vertex Shader: phong_vs
            Fragment Shader: phong_fs
            Attributes:
                ATTR_phong_in_pos => 0
                ATTR_phong_in_normal => 1
                ATTR_phong_in_uv => 2
                ATTR_phong_in_color => 3
        Bindings:
            Uniform block 'phong_vs_params':
                C struct: phong_vs_params_t
                Bind slot: UB_phong_vs_params => 0
            Uniform block 'phong_fs_params':
                C struct: phong_fs_params_t
                Bind slot: UB_phong_fs_params => 1
    */
    public const int ATTR_phong_in_pos = 0;
    public const int ATTR_phong_in_normal = 1;
    public const int ATTR_phong_in_uv = 2;
    public const int ATTR_phong_in_color = 3;
    public const int UB_phong_vs_params = 0;
    public const int UB_phong_fs_params = 1;
    
[StructLayout(LayoutKind.Sequential)]
    public struct phong_vs_params_t {
        public phong_vs_params_t(){}
        public System.Numerics.Matrix4x4 mvp;
        public System.Numerics.Matrix4x4 model;
    };
    
[StructLayout(LayoutKind.Sequential)]
    public struct phong_fs_params_t {
        public phong_fs_params_t(){}
        public System.Numerics.Vector4 ambient_and_count;
        #pragma warning disable 169
        public struct lights_dataCollection {
            public ref System.Numerics.Vector4 this[int index] => ref MemoryMarshal.CreateSpan(ref _item0, 1024)[index];
            private System.Numerics.Vector4 _item0;
            private System.Numerics.Vector4 _item1;
            private System.Numerics.Vector4 _item2;
            private System.Numerics.Vector4 _item3;
            private System.Numerics.Vector4 _item4;
            private System.Numerics.Vector4 _item5;
            private System.Numerics.Vector4 _item6;
            private System.Numerics.Vector4 _item7;
            private System.Numerics.Vector4 _item8;
            private System.Numerics.Vector4 _item9;
            private System.Numerics.Vector4 _item10;
            private System.Numerics.Vector4 _item11;
            private System.Numerics.Vector4 _item12;
            private System.Numerics.Vector4 _item13;
            private System.Numerics.Vector4 _item14;
            private System.Numerics.Vector4 _item15;
            private System.Numerics.Vector4 _item16;
            private System.Numerics.Vector4 _item17;
            private System.Numerics.Vector4 _item18;
            private System.Numerics.Vector4 _item19;
            private System.Numerics.Vector4 _item20;
            private System.Numerics.Vector4 _item21;
            private System.Numerics.Vector4 _item22;
            private System.Numerics.Vector4 _item23;
            private System.Numerics.Vector4 _item24;
            private System.Numerics.Vector4 _item25;
            private System.Numerics.Vector4 _item26;
            private System.Numerics.Vector4 _item27;
            private System.Numerics.Vector4 _item28;
            private System.Numerics.Vector4 _item29;
            private System.Numerics.Vector4 _item30;
            private System.Numerics.Vector4 _item31;
            private System.Numerics.Vector4 _item32;
            private System.Numerics.Vector4 _item33;
            private System.Numerics.Vector4 _item34;
            private System.Numerics.Vector4 _item35;
            private System.Numerics.Vector4 _item36;
            private System.Numerics.Vector4 _item37;
            private System.Numerics.Vector4 _item38;
            private System.Numerics.Vector4 _item39;
            private System.Numerics.Vector4 _item40;
            private System.Numerics.Vector4 _item41;
            private System.Numerics.Vector4 _item42;
            private System.Numerics.Vector4 _item43;
            private System.Numerics.Vector4 _item44;
            private System.Numerics.Vector4 _item45;
            private System.Numerics.Vector4 _item46;
            private System.Numerics.Vector4 _item47;
            private System.Numerics.Vector4 _item48;
            private System.Numerics.Vector4 _item49;
            private System.Numerics.Vector4 _item50;
            private System.Numerics.Vector4 _item51;
            private System.Numerics.Vector4 _item52;
            private System.Numerics.Vector4 _item53;
            private System.Numerics.Vector4 _item54;
            private System.Numerics.Vector4 _item55;
            private System.Numerics.Vector4 _item56;
            private System.Numerics.Vector4 _item57;
            private System.Numerics.Vector4 _item58;
            private System.Numerics.Vector4 _item59;
            private System.Numerics.Vector4 _item60;
            private System.Numerics.Vector4 _item61;
            private System.Numerics.Vector4 _item62;
            private System.Numerics.Vector4 _item63;
            private System.Numerics.Vector4 _item64;
            private System.Numerics.Vector4 _item65;
            private System.Numerics.Vector4 _item66;
            private System.Numerics.Vector4 _item67;
            private System.Numerics.Vector4 _item68;
            private System.Numerics.Vector4 _item69;
            private System.Numerics.Vector4 _item70;
            private System.Numerics.Vector4 _item71;
            private System.Numerics.Vector4 _item72;
            private System.Numerics.Vector4 _item73;
            private System.Numerics.Vector4 _item74;
            private System.Numerics.Vector4 _item75;
            private System.Numerics.Vector4 _item76;
            private System.Numerics.Vector4 _item77;
            private System.Numerics.Vector4 _item78;
            private System.Numerics.Vector4 _item79;
            private System.Numerics.Vector4 _item80;
            private System.Numerics.Vector4 _item81;
            private System.Numerics.Vector4 _item82;
            private System.Numerics.Vector4 _item83;
            private System.Numerics.Vector4 _item84;
            private System.Numerics.Vector4 _item85;
            private System.Numerics.Vector4 _item86;
            private System.Numerics.Vector4 _item87;
            private System.Numerics.Vector4 _item88;
            private System.Numerics.Vector4 _item89;
            private System.Numerics.Vector4 _item90;
            private System.Numerics.Vector4 _item91;
            private System.Numerics.Vector4 _item92;
            private System.Numerics.Vector4 _item93;
            private System.Numerics.Vector4 _item94;
            private System.Numerics.Vector4 _item95;
            private System.Numerics.Vector4 _item96;
            private System.Numerics.Vector4 _item97;
            private System.Numerics.Vector4 _item98;
            private System.Numerics.Vector4 _item99;
            private System.Numerics.Vector4 _item100;
            private System.Numerics.Vector4 _item101;
            private System.Numerics.Vector4 _item102;
            private System.Numerics.Vector4 _item103;
            private System.Numerics.Vector4 _item104;
            private System.Numerics.Vector4 _item105;
            private System.Numerics.Vector4 _item106;
            private System.Numerics.Vector4 _item107;
            private System.Numerics.Vector4 _item108;
            private System.Numerics.Vector4 _item109;
            private System.Numerics.Vector4 _item110;
            private System.Numerics.Vector4 _item111;
            private System.Numerics.Vector4 _item112;
            private System.Numerics.Vector4 _item113;
            private System.Numerics.Vector4 _item114;
            private System.Numerics.Vector4 _item115;
            private System.Numerics.Vector4 _item116;
            private System.Numerics.Vector4 _item117;
            private System.Numerics.Vector4 _item118;
            private System.Numerics.Vector4 _item119;
            private System.Numerics.Vector4 _item120;
            private System.Numerics.Vector4 _item121;
            private System.Numerics.Vector4 _item122;
            private System.Numerics.Vector4 _item123;
            private System.Numerics.Vector4 _item124;
            private System.Numerics.Vector4 _item125;
            private System.Numerics.Vector4 _item126;
            private System.Numerics.Vector4 _item127;
            private System.Numerics.Vector4 _item128;
            private System.Numerics.Vector4 _item129;
            private System.Numerics.Vector4 _item130;
            private System.Numerics.Vector4 _item131;
            private System.Numerics.Vector4 _item132;
            private System.Numerics.Vector4 _item133;
            private System.Numerics.Vector4 _item134;
            private System.Numerics.Vector4 _item135;
            private System.Numerics.Vector4 _item136;
            private System.Numerics.Vector4 _item137;
            private System.Numerics.Vector4 _item138;
            private System.Numerics.Vector4 _item139;
            private System.Numerics.Vector4 _item140;
            private System.Numerics.Vector4 _item141;
            private System.Numerics.Vector4 _item142;
            private System.Numerics.Vector4 _item143;
            private System.Numerics.Vector4 _item144;
            private System.Numerics.Vector4 _item145;
            private System.Numerics.Vector4 _item146;
            private System.Numerics.Vector4 _item147;
            private System.Numerics.Vector4 _item148;
            private System.Numerics.Vector4 _item149;
            private System.Numerics.Vector4 _item150;
            private System.Numerics.Vector4 _item151;
            private System.Numerics.Vector4 _item152;
            private System.Numerics.Vector4 _item153;
            private System.Numerics.Vector4 _item154;
            private System.Numerics.Vector4 _item155;
            private System.Numerics.Vector4 _item156;
            private System.Numerics.Vector4 _item157;
            private System.Numerics.Vector4 _item158;
            private System.Numerics.Vector4 _item159;
            private System.Numerics.Vector4 _item160;
            private System.Numerics.Vector4 _item161;
            private System.Numerics.Vector4 _item162;
            private System.Numerics.Vector4 _item163;
            private System.Numerics.Vector4 _item164;
            private System.Numerics.Vector4 _item165;
            private System.Numerics.Vector4 _item166;
            private System.Numerics.Vector4 _item167;
            private System.Numerics.Vector4 _item168;
            private System.Numerics.Vector4 _item169;
            private System.Numerics.Vector4 _item170;
            private System.Numerics.Vector4 _item171;
            private System.Numerics.Vector4 _item172;
            private System.Numerics.Vector4 _item173;
            private System.Numerics.Vector4 _item174;
            private System.Numerics.Vector4 _item175;
            private System.Numerics.Vector4 _item176;
            private System.Numerics.Vector4 _item177;
            private System.Numerics.Vector4 _item178;
            private System.Numerics.Vector4 _item179;
            private System.Numerics.Vector4 _item180;
            private System.Numerics.Vector4 _item181;
            private System.Numerics.Vector4 _item182;
            private System.Numerics.Vector4 _item183;
            private System.Numerics.Vector4 _item184;
            private System.Numerics.Vector4 _item185;
            private System.Numerics.Vector4 _item186;
            private System.Numerics.Vector4 _item187;
            private System.Numerics.Vector4 _item188;
            private System.Numerics.Vector4 _item189;
            private System.Numerics.Vector4 _item190;
            private System.Numerics.Vector4 _item191;
            private System.Numerics.Vector4 _item192;
            private System.Numerics.Vector4 _item193;
            private System.Numerics.Vector4 _item194;
            private System.Numerics.Vector4 _item195;
            private System.Numerics.Vector4 _item196;
            private System.Numerics.Vector4 _item197;
            private System.Numerics.Vector4 _item198;
            private System.Numerics.Vector4 _item199;
            private System.Numerics.Vector4 _item200;
            private System.Numerics.Vector4 _item201;
            private System.Numerics.Vector4 _item202;
            private System.Numerics.Vector4 _item203;
            private System.Numerics.Vector4 _item204;
            private System.Numerics.Vector4 _item205;
            private System.Numerics.Vector4 _item206;
            private System.Numerics.Vector4 _item207;
            private System.Numerics.Vector4 _item208;
            private System.Numerics.Vector4 _item209;
            private System.Numerics.Vector4 _item210;
            private System.Numerics.Vector4 _item211;
            private System.Numerics.Vector4 _item212;
            private System.Numerics.Vector4 _item213;
            private System.Numerics.Vector4 _item214;
            private System.Numerics.Vector4 _item215;
            private System.Numerics.Vector4 _item216;
            private System.Numerics.Vector4 _item217;
            private System.Numerics.Vector4 _item218;
            private System.Numerics.Vector4 _item219;
            private System.Numerics.Vector4 _item220;
            private System.Numerics.Vector4 _item221;
            private System.Numerics.Vector4 _item222;
            private System.Numerics.Vector4 _item223;
            private System.Numerics.Vector4 _item224;
            private System.Numerics.Vector4 _item225;
            private System.Numerics.Vector4 _item226;
            private System.Numerics.Vector4 _item227;
            private System.Numerics.Vector4 _item228;
            private System.Numerics.Vector4 _item229;
            private System.Numerics.Vector4 _item230;
            private System.Numerics.Vector4 _item231;
            private System.Numerics.Vector4 _item232;
            private System.Numerics.Vector4 _item233;
            private System.Numerics.Vector4 _item234;
            private System.Numerics.Vector4 _item235;
            private System.Numerics.Vector4 _item236;
            private System.Numerics.Vector4 _item237;
            private System.Numerics.Vector4 _item238;
            private System.Numerics.Vector4 _item239;
            private System.Numerics.Vector4 _item240;
            private System.Numerics.Vector4 _item241;
            private System.Numerics.Vector4 _item242;
            private System.Numerics.Vector4 _item243;
            private System.Numerics.Vector4 _item244;
            private System.Numerics.Vector4 _item245;
            private System.Numerics.Vector4 _item246;
            private System.Numerics.Vector4 _item247;
            private System.Numerics.Vector4 _item248;
            private System.Numerics.Vector4 _item249;
            private System.Numerics.Vector4 _item250;
            private System.Numerics.Vector4 _item251;
            private System.Numerics.Vector4 _item252;
            private System.Numerics.Vector4 _item253;
            private System.Numerics.Vector4 _item254;
            private System.Numerics.Vector4 _item255;
            private System.Numerics.Vector4 _item256;
            private System.Numerics.Vector4 _item257;
            private System.Numerics.Vector4 _item258;
            private System.Numerics.Vector4 _item259;
            private System.Numerics.Vector4 _item260;
            private System.Numerics.Vector4 _item261;
            private System.Numerics.Vector4 _item262;
            private System.Numerics.Vector4 _item263;
            private System.Numerics.Vector4 _item264;
            private System.Numerics.Vector4 _item265;
            private System.Numerics.Vector4 _item266;
            private System.Numerics.Vector4 _item267;
            private System.Numerics.Vector4 _item268;
            private System.Numerics.Vector4 _item269;
            private System.Numerics.Vector4 _item270;
            private System.Numerics.Vector4 _item271;
            private System.Numerics.Vector4 _item272;
            private System.Numerics.Vector4 _item273;
            private System.Numerics.Vector4 _item274;
            private System.Numerics.Vector4 _item275;
            private System.Numerics.Vector4 _item276;
            private System.Numerics.Vector4 _item277;
            private System.Numerics.Vector4 _item278;
            private System.Numerics.Vector4 _item279;
            private System.Numerics.Vector4 _item280;
            private System.Numerics.Vector4 _item281;
            private System.Numerics.Vector4 _item282;
            private System.Numerics.Vector4 _item283;
            private System.Numerics.Vector4 _item284;
            private System.Numerics.Vector4 _item285;
            private System.Numerics.Vector4 _item286;
            private System.Numerics.Vector4 _item287;
            private System.Numerics.Vector4 _item288;
            private System.Numerics.Vector4 _item289;
            private System.Numerics.Vector4 _item290;
            private System.Numerics.Vector4 _item291;
            private System.Numerics.Vector4 _item292;
            private System.Numerics.Vector4 _item293;
            private System.Numerics.Vector4 _item294;
            private System.Numerics.Vector4 _item295;
            private System.Numerics.Vector4 _item296;
            private System.Numerics.Vector4 _item297;
            private System.Numerics.Vector4 _item298;
            private System.Numerics.Vector4 _item299;
            private System.Numerics.Vector4 _item300;
            private System.Numerics.Vector4 _item301;
            private System.Numerics.Vector4 _item302;
            private System.Numerics.Vector4 _item303;
            private System.Numerics.Vector4 _item304;
            private System.Numerics.Vector4 _item305;
            private System.Numerics.Vector4 _item306;
            private System.Numerics.Vector4 _item307;
            private System.Numerics.Vector4 _item308;
            private System.Numerics.Vector4 _item309;
            private System.Numerics.Vector4 _item310;
            private System.Numerics.Vector4 _item311;
            private System.Numerics.Vector4 _item312;
            private System.Numerics.Vector4 _item313;
            private System.Numerics.Vector4 _item314;
            private System.Numerics.Vector4 _item315;
            private System.Numerics.Vector4 _item316;
            private System.Numerics.Vector4 _item317;
            private System.Numerics.Vector4 _item318;
            private System.Numerics.Vector4 _item319;
            private System.Numerics.Vector4 _item320;
            private System.Numerics.Vector4 _item321;
            private System.Numerics.Vector4 _item322;
            private System.Numerics.Vector4 _item323;
            private System.Numerics.Vector4 _item324;
            private System.Numerics.Vector4 _item325;
            private System.Numerics.Vector4 _item326;
            private System.Numerics.Vector4 _item327;
            private System.Numerics.Vector4 _item328;
            private System.Numerics.Vector4 _item329;
            private System.Numerics.Vector4 _item330;
            private System.Numerics.Vector4 _item331;
            private System.Numerics.Vector4 _item332;
            private System.Numerics.Vector4 _item333;
            private System.Numerics.Vector4 _item334;
            private System.Numerics.Vector4 _item335;
            private System.Numerics.Vector4 _item336;
            private System.Numerics.Vector4 _item337;
            private System.Numerics.Vector4 _item338;
            private System.Numerics.Vector4 _item339;
            private System.Numerics.Vector4 _item340;
            private System.Numerics.Vector4 _item341;
            private System.Numerics.Vector4 _item342;
            private System.Numerics.Vector4 _item343;
            private System.Numerics.Vector4 _item344;
            private System.Numerics.Vector4 _item345;
            private System.Numerics.Vector4 _item346;
            private System.Numerics.Vector4 _item347;
            private System.Numerics.Vector4 _item348;
            private System.Numerics.Vector4 _item349;
            private System.Numerics.Vector4 _item350;
            private System.Numerics.Vector4 _item351;
            private System.Numerics.Vector4 _item352;
            private System.Numerics.Vector4 _item353;
            private System.Numerics.Vector4 _item354;
            private System.Numerics.Vector4 _item355;
            private System.Numerics.Vector4 _item356;
            private System.Numerics.Vector4 _item357;
            private System.Numerics.Vector4 _item358;
            private System.Numerics.Vector4 _item359;
            private System.Numerics.Vector4 _item360;
            private System.Numerics.Vector4 _item361;
            private System.Numerics.Vector4 _item362;
            private System.Numerics.Vector4 _item363;
            private System.Numerics.Vector4 _item364;
            private System.Numerics.Vector4 _item365;
            private System.Numerics.Vector4 _item366;
            private System.Numerics.Vector4 _item367;
            private System.Numerics.Vector4 _item368;
            private System.Numerics.Vector4 _item369;
            private System.Numerics.Vector4 _item370;
            private System.Numerics.Vector4 _item371;
            private System.Numerics.Vector4 _item372;
            private System.Numerics.Vector4 _item373;
            private System.Numerics.Vector4 _item374;
            private System.Numerics.Vector4 _item375;
            private System.Numerics.Vector4 _item376;
            private System.Numerics.Vector4 _item377;
            private System.Numerics.Vector4 _item378;
            private System.Numerics.Vector4 _item379;
            private System.Numerics.Vector4 _item380;
            private System.Numerics.Vector4 _item381;
            private System.Numerics.Vector4 _item382;
            private System.Numerics.Vector4 _item383;
            private System.Numerics.Vector4 _item384;
            private System.Numerics.Vector4 _item385;
            private System.Numerics.Vector4 _item386;
            private System.Numerics.Vector4 _item387;
            private System.Numerics.Vector4 _item388;
            private System.Numerics.Vector4 _item389;
            private System.Numerics.Vector4 _item390;
            private System.Numerics.Vector4 _item391;
            private System.Numerics.Vector4 _item392;
            private System.Numerics.Vector4 _item393;
            private System.Numerics.Vector4 _item394;
            private System.Numerics.Vector4 _item395;
            private System.Numerics.Vector4 _item396;
            private System.Numerics.Vector4 _item397;
            private System.Numerics.Vector4 _item398;
            private System.Numerics.Vector4 _item399;
            private System.Numerics.Vector4 _item400;
            private System.Numerics.Vector4 _item401;
            private System.Numerics.Vector4 _item402;
            private System.Numerics.Vector4 _item403;
            private System.Numerics.Vector4 _item404;
            private System.Numerics.Vector4 _item405;
            private System.Numerics.Vector4 _item406;
            private System.Numerics.Vector4 _item407;
            private System.Numerics.Vector4 _item408;
            private System.Numerics.Vector4 _item409;
            private System.Numerics.Vector4 _item410;
            private System.Numerics.Vector4 _item411;
            private System.Numerics.Vector4 _item412;
            private System.Numerics.Vector4 _item413;
            private System.Numerics.Vector4 _item414;
            private System.Numerics.Vector4 _item415;
            private System.Numerics.Vector4 _item416;
            private System.Numerics.Vector4 _item417;
            private System.Numerics.Vector4 _item418;
            private System.Numerics.Vector4 _item419;
            private System.Numerics.Vector4 _item420;
            private System.Numerics.Vector4 _item421;
            private System.Numerics.Vector4 _item422;
            private System.Numerics.Vector4 _item423;
            private System.Numerics.Vector4 _item424;
            private System.Numerics.Vector4 _item425;
            private System.Numerics.Vector4 _item426;
            private System.Numerics.Vector4 _item427;
            private System.Numerics.Vector4 _item428;
            private System.Numerics.Vector4 _item429;
            private System.Numerics.Vector4 _item430;
            private System.Numerics.Vector4 _item431;
            private System.Numerics.Vector4 _item432;
            private System.Numerics.Vector4 _item433;
            private System.Numerics.Vector4 _item434;
            private System.Numerics.Vector4 _item435;
            private System.Numerics.Vector4 _item436;
            private System.Numerics.Vector4 _item437;
            private System.Numerics.Vector4 _item438;
            private System.Numerics.Vector4 _item439;
            private System.Numerics.Vector4 _item440;
            private System.Numerics.Vector4 _item441;
            private System.Numerics.Vector4 _item442;
            private System.Numerics.Vector4 _item443;
            private System.Numerics.Vector4 _item444;
            private System.Numerics.Vector4 _item445;
            private System.Numerics.Vector4 _item446;
            private System.Numerics.Vector4 _item447;
            private System.Numerics.Vector4 _item448;
            private System.Numerics.Vector4 _item449;
            private System.Numerics.Vector4 _item450;
            private System.Numerics.Vector4 _item451;
            private System.Numerics.Vector4 _item452;
            private System.Numerics.Vector4 _item453;
            private System.Numerics.Vector4 _item454;
            private System.Numerics.Vector4 _item455;
            private System.Numerics.Vector4 _item456;
            private System.Numerics.Vector4 _item457;
            private System.Numerics.Vector4 _item458;
            private System.Numerics.Vector4 _item459;
            private System.Numerics.Vector4 _item460;
            private System.Numerics.Vector4 _item461;
            private System.Numerics.Vector4 _item462;
            private System.Numerics.Vector4 _item463;
            private System.Numerics.Vector4 _item464;
            private System.Numerics.Vector4 _item465;
            private System.Numerics.Vector4 _item466;
            private System.Numerics.Vector4 _item467;
            private System.Numerics.Vector4 _item468;
            private System.Numerics.Vector4 _item469;
            private System.Numerics.Vector4 _item470;
            private System.Numerics.Vector4 _item471;
            private System.Numerics.Vector4 _item472;
            private System.Numerics.Vector4 _item473;
            private System.Numerics.Vector4 _item474;
            private System.Numerics.Vector4 _item475;
            private System.Numerics.Vector4 _item476;
            private System.Numerics.Vector4 _item477;
            private System.Numerics.Vector4 _item478;
            private System.Numerics.Vector4 _item479;
            private System.Numerics.Vector4 _item480;
            private System.Numerics.Vector4 _item481;
            private System.Numerics.Vector4 _item482;
            private System.Numerics.Vector4 _item483;
            private System.Numerics.Vector4 _item484;
            private System.Numerics.Vector4 _item485;
            private System.Numerics.Vector4 _item486;
            private System.Numerics.Vector4 _item487;
            private System.Numerics.Vector4 _item488;
            private System.Numerics.Vector4 _item489;
            private System.Numerics.Vector4 _item490;
            private System.Numerics.Vector4 _item491;
            private System.Numerics.Vector4 _item492;
            private System.Numerics.Vector4 _item493;
            private System.Numerics.Vector4 _item494;
            private System.Numerics.Vector4 _item495;
            private System.Numerics.Vector4 _item496;
            private System.Numerics.Vector4 _item497;
            private System.Numerics.Vector4 _item498;
            private System.Numerics.Vector4 _item499;
            private System.Numerics.Vector4 _item500;
            private System.Numerics.Vector4 _item501;
            private System.Numerics.Vector4 _item502;
            private System.Numerics.Vector4 _item503;
            private System.Numerics.Vector4 _item504;
            private System.Numerics.Vector4 _item505;
            private System.Numerics.Vector4 _item506;
            private System.Numerics.Vector4 _item507;
            private System.Numerics.Vector4 _item508;
            private System.Numerics.Vector4 _item509;
            private System.Numerics.Vector4 _item510;
            private System.Numerics.Vector4 _item511;
            private System.Numerics.Vector4 _item512;
            private System.Numerics.Vector4 _item513;
            private System.Numerics.Vector4 _item514;
            private System.Numerics.Vector4 _item515;
            private System.Numerics.Vector4 _item516;
            private System.Numerics.Vector4 _item517;
            private System.Numerics.Vector4 _item518;
            private System.Numerics.Vector4 _item519;
            private System.Numerics.Vector4 _item520;
            private System.Numerics.Vector4 _item521;
            private System.Numerics.Vector4 _item522;
            private System.Numerics.Vector4 _item523;
            private System.Numerics.Vector4 _item524;
            private System.Numerics.Vector4 _item525;
            private System.Numerics.Vector4 _item526;
            private System.Numerics.Vector4 _item527;
            private System.Numerics.Vector4 _item528;
            private System.Numerics.Vector4 _item529;
            private System.Numerics.Vector4 _item530;
            private System.Numerics.Vector4 _item531;
            private System.Numerics.Vector4 _item532;
            private System.Numerics.Vector4 _item533;
            private System.Numerics.Vector4 _item534;
            private System.Numerics.Vector4 _item535;
            private System.Numerics.Vector4 _item536;
            private System.Numerics.Vector4 _item537;
            private System.Numerics.Vector4 _item538;
            private System.Numerics.Vector4 _item539;
            private System.Numerics.Vector4 _item540;
            private System.Numerics.Vector4 _item541;
            private System.Numerics.Vector4 _item542;
            private System.Numerics.Vector4 _item543;
            private System.Numerics.Vector4 _item544;
            private System.Numerics.Vector4 _item545;
            private System.Numerics.Vector4 _item546;
            private System.Numerics.Vector4 _item547;
            private System.Numerics.Vector4 _item548;
            private System.Numerics.Vector4 _item549;
            private System.Numerics.Vector4 _item550;
            private System.Numerics.Vector4 _item551;
            private System.Numerics.Vector4 _item552;
            private System.Numerics.Vector4 _item553;
            private System.Numerics.Vector4 _item554;
            private System.Numerics.Vector4 _item555;
            private System.Numerics.Vector4 _item556;
            private System.Numerics.Vector4 _item557;
            private System.Numerics.Vector4 _item558;
            private System.Numerics.Vector4 _item559;
            private System.Numerics.Vector4 _item560;
            private System.Numerics.Vector4 _item561;
            private System.Numerics.Vector4 _item562;
            private System.Numerics.Vector4 _item563;
            private System.Numerics.Vector4 _item564;
            private System.Numerics.Vector4 _item565;
            private System.Numerics.Vector4 _item566;
            private System.Numerics.Vector4 _item567;
            private System.Numerics.Vector4 _item568;
            private System.Numerics.Vector4 _item569;
            private System.Numerics.Vector4 _item570;
            private System.Numerics.Vector4 _item571;
            private System.Numerics.Vector4 _item572;
            private System.Numerics.Vector4 _item573;
            private System.Numerics.Vector4 _item574;
            private System.Numerics.Vector4 _item575;
            private System.Numerics.Vector4 _item576;
            private System.Numerics.Vector4 _item577;
            private System.Numerics.Vector4 _item578;
            private System.Numerics.Vector4 _item579;
            private System.Numerics.Vector4 _item580;
            private System.Numerics.Vector4 _item581;
            private System.Numerics.Vector4 _item582;
            private System.Numerics.Vector4 _item583;
            private System.Numerics.Vector4 _item584;
            private System.Numerics.Vector4 _item585;
            private System.Numerics.Vector4 _item586;
            private System.Numerics.Vector4 _item587;
            private System.Numerics.Vector4 _item588;
            private System.Numerics.Vector4 _item589;
            private System.Numerics.Vector4 _item590;
            private System.Numerics.Vector4 _item591;
            private System.Numerics.Vector4 _item592;
            private System.Numerics.Vector4 _item593;
            private System.Numerics.Vector4 _item594;
            private System.Numerics.Vector4 _item595;
            private System.Numerics.Vector4 _item596;
            private System.Numerics.Vector4 _item597;
            private System.Numerics.Vector4 _item598;
            private System.Numerics.Vector4 _item599;
            private System.Numerics.Vector4 _item600;
            private System.Numerics.Vector4 _item601;
            private System.Numerics.Vector4 _item602;
            private System.Numerics.Vector4 _item603;
            private System.Numerics.Vector4 _item604;
            private System.Numerics.Vector4 _item605;
            private System.Numerics.Vector4 _item606;
            private System.Numerics.Vector4 _item607;
            private System.Numerics.Vector4 _item608;
            private System.Numerics.Vector4 _item609;
            private System.Numerics.Vector4 _item610;
            private System.Numerics.Vector4 _item611;
            private System.Numerics.Vector4 _item612;
            private System.Numerics.Vector4 _item613;
            private System.Numerics.Vector4 _item614;
            private System.Numerics.Vector4 _item615;
            private System.Numerics.Vector4 _item616;
            private System.Numerics.Vector4 _item617;
            private System.Numerics.Vector4 _item618;
            private System.Numerics.Vector4 _item619;
            private System.Numerics.Vector4 _item620;
            private System.Numerics.Vector4 _item621;
            private System.Numerics.Vector4 _item622;
            private System.Numerics.Vector4 _item623;
            private System.Numerics.Vector4 _item624;
            private System.Numerics.Vector4 _item625;
            private System.Numerics.Vector4 _item626;
            private System.Numerics.Vector4 _item627;
            private System.Numerics.Vector4 _item628;
            private System.Numerics.Vector4 _item629;
            private System.Numerics.Vector4 _item630;
            private System.Numerics.Vector4 _item631;
            private System.Numerics.Vector4 _item632;
            private System.Numerics.Vector4 _item633;
            private System.Numerics.Vector4 _item634;
            private System.Numerics.Vector4 _item635;
            private System.Numerics.Vector4 _item636;
            private System.Numerics.Vector4 _item637;
            private System.Numerics.Vector4 _item638;
            private System.Numerics.Vector4 _item639;
            private System.Numerics.Vector4 _item640;
            private System.Numerics.Vector4 _item641;
            private System.Numerics.Vector4 _item642;
            private System.Numerics.Vector4 _item643;
            private System.Numerics.Vector4 _item644;
            private System.Numerics.Vector4 _item645;
            private System.Numerics.Vector4 _item646;
            private System.Numerics.Vector4 _item647;
            private System.Numerics.Vector4 _item648;
            private System.Numerics.Vector4 _item649;
            private System.Numerics.Vector4 _item650;
            private System.Numerics.Vector4 _item651;
            private System.Numerics.Vector4 _item652;
            private System.Numerics.Vector4 _item653;
            private System.Numerics.Vector4 _item654;
            private System.Numerics.Vector4 _item655;
            private System.Numerics.Vector4 _item656;
            private System.Numerics.Vector4 _item657;
            private System.Numerics.Vector4 _item658;
            private System.Numerics.Vector4 _item659;
            private System.Numerics.Vector4 _item660;
            private System.Numerics.Vector4 _item661;
            private System.Numerics.Vector4 _item662;
            private System.Numerics.Vector4 _item663;
            private System.Numerics.Vector4 _item664;
            private System.Numerics.Vector4 _item665;
            private System.Numerics.Vector4 _item666;
            private System.Numerics.Vector4 _item667;
            private System.Numerics.Vector4 _item668;
            private System.Numerics.Vector4 _item669;
            private System.Numerics.Vector4 _item670;
            private System.Numerics.Vector4 _item671;
            private System.Numerics.Vector4 _item672;
            private System.Numerics.Vector4 _item673;
            private System.Numerics.Vector4 _item674;
            private System.Numerics.Vector4 _item675;
            private System.Numerics.Vector4 _item676;
            private System.Numerics.Vector4 _item677;
            private System.Numerics.Vector4 _item678;
            private System.Numerics.Vector4 _item679;
            private System.Numerics.Vector4 _item680;
            private System.Numerics.Vector4 _item681;
            private System.Numerics.Vector4 _item682;
            private System.Numerics.Vector4 _item683;
            private System.Numerics.Vector4 _item684;
            private System.Numerics.Vector4 _item685;
            private System.Numerics.Vector4 _item686;
            private System.Numerics.Vector4 _item687;
            private System.Numerics.Vector4 _item688;
            private System.Numerics.Vector4 _item689;
            private System.Numerics.Vector4 _item690;
            private System.Numerics.Vector4 _item691;
            private System.Numerics.Vector4 _item692;
            private System.Numerics.Vector4 _item693;
            private System.Numerics.Vector4 _item694;
            private System.Numerics.Vector4 _item695;
            private System.Numerics.Vector4 _item696;
            private System.Numerics.Vector4 _item697;
            private System.Numerics.Vector4 _item698;
            private System.Numerics.Vector4 _item699;
            private System.Numerics.Vector4 _item700;
            private System.Numerics.Vector4 _item701;
            private System.Numerics.Vector4 _item702;
            private System.Numerics.Vector4 _item703;
            private System.Numerics.Vector4 _item704;
            private System.Numerics.Vector4 _item705;
            private System.Numerics.Vector4 _item706;
            private System.Numerics.Vector4 _item707;
            private System.Numerics.Vector4 _item708;
            private System.Numerics.Vector4 _item709;
            private System.Numerics.Vector4 _item710;
            private System.Numerics.Vector4 _item711;
            private System.Numerics.Vector4 _item712;
            private System.Numerics.Vector4 _item713;
            private System.Numerics.Vector4 _item714;
            private System.Numerics.Vector4 _item715;
            private System.Numerics.Vector4 _item716;
            private System.Numerics.Vector4 _item717;
            private System.Numerics.Vector4 _item718;
            private System.Numerics.Vector4 _item719;
            private System.Numerics.Vector4 _item720;
            private System.Numerics.Vector4 _item721;
            private System.Numerics.Vector4 _item722;
            private System.Numerics.Vector4 _item723;
            private System.Numerics.Vector4 _item724;
            private System.Numerics.Vector4 _item725;
            private System.Numerics.Vector4 _item726;
            private System.Numerics.Vector4 _item727;
            private System.Numerics.Vector4 _item728;
            private System.Numerics.Vector4 _item729;
            private System.Numerics.Vector4 _item730;
            private System.Numerics.Vector4 _item731;
            private System.Numerics.Vector4 _item732;
            private System.Numerics.Vector4 _item733;
            private System.Numerics.Vector4 _item734;
            private System.Numerics.Vector4 _item735;
            private System.Numerics.Vector4 _item736;
            private System.Numerics.Vector4 _item737;
            private System.Numerics.Vector4 _item738;
            private System.Numerics.Vector4 _item739;
            private System.Numerics.Vector4 _item740;
            private System.Numerics.Vector4 _item741;
            private System.Numerics.Vector4 _item742;
            private System.Numerics.Vector4 _item743;
            private System.Numerics.Vector4 _item744;
            private System.Numerics.Vector4 _item745;
            private System.Numerics.Vector4 _item746;
            private System.Numerics.Vector4 _item747;
            private System.Numerics.Vector4 _item748;
            private System.Numerics.Vector4 _item749;
            private System.Numerics.Vector4 _item750;
            private System.Numerics.Vector4 _item751;
            private System.Numerics.Vector4 _item752;
            private System.Numerics.Vector4 _item753;
            private System.Numerics.Vector4 _item754;
            private System.Numerics.Vector4 _item755;
            private System.Numerics.Vector4 _item756;
            private System.Numerics.Vector4 _item757;
            private System.Numerics.Vector4 _item758;
            private System.Numerics.Vector4 _item759;
            private System.Numerics.Vector4 _item760;
            private System.Numerics.Vector4 _item761;
            private System.Numerics.Vector4 _item762;
            private System.Numerics.Vector4 _item763;
            private System.Numerics.Vector4 _item764;
            private System.Numerics.Vector4 _item765;
            private System.Numerics.Vector4 _item766;
            private System.Numerics.Vector4 _item767;
            private System.Numerics.Vector4 _item768;
            private System.Numerics.Vector4 _item769;
            private System.Numerics.Vector4 _item770;
            private System.Numerics.Vector4 _item771;
            private System.Numerics.Vector4 _item772;
            private System.Numerics.Vector4 _item773;
            private System.Numerics.Vector4 _item774;
            private System.Numerics.Vector4 _item775;
            private System.Numerics.Vector4 _item776;
            private System.Numerics.Vector4 _item777;
            private System.Numerics.Vector4 _item778;
            private System.Numerics.Vector4 _item779;
            private System.Numerics.Vector4 _item780;
            private System.Numerics.Vector4 _item781;
            private System.Numerics.Vector4 _item782;
            private System.Numerics.Vector4 _item783;
            private System.Numerics.Vector4 _item784;
            private System.Numerics.Vector4 _item785;
            private System.Numerics.Vector4 _item786;
            private System.Numerics.Vector4 _item787;
            private System.Numerics.Vector4 _item788;
            private System.Numerics.Vector4 _item789;
            private System.Numerics.Vector4 _item790;
            private System.Numerics.Vector4 _item791;
            private System.Numerics.Vector4 _item792;
            private System.Numerics.Vector4 _item793;
            private System.Numerics.Vector4 _item794;
            private System.Numerics.Vector4 _item795;
            private System.Numerics.Vector4 _item796;
            private System.Numerics.Vector4 _item797;
            private System.Numerics.Vector4 _item798;
            private System.Numerics.Vector4 _item799;
            private System.Numerics.Vector4 _item800;
            private System.Numerics.Vector4 _item801;
            private System.Numerics.Vector4 _item802;
            private System.Numerics.Vector4 _item803;
            private System.Numerics.Vector4 _item804;
            private System.Numerics.Vector4 _item805;
            private System.Numerics.Vector4 _item806;
            private System.Numerics.Vector4 _item807;
            private System.Numerics.Vector4 _item808;
            private System.Numerics.Vector4 _item809;
            private System.Numerics.Vector4 _item810;
            private System.Numerics.Vector4 _item811;
            private System.Numerics.Vector4 _item812;
            private System.Numerics.Vector4 _item813;
            private System.Numerics.Vector4 _item814;
            private System.Numerics.Vector4 _item815;
            private System.Numerics.Vector4 _item816;
            private System.Numerics.Vector4 _item817;
            private System.Numerics.Vector4 _item818;
            private System.Numerics.Vector4 _item819;
            private System.Numerics.Vector4 _item820;
            private System.Numerics.Vector4 _item821;
            private System.Numerics.Vector4 _item822;
            private System.Numerics.Vector4 _item823;
            private System.Numerics.Vector4 _item824;
            private System.Numerics.Vector4 _item825;
            private System.Numerics.Vector4 _item826;
            private System.Numerics.Vector4 _item827;
            private System.Numerics.Vector4 _item828;
            private System.Numerics.Vector4 _item829;
            private System.Numerics.Vector4 _item830;
            private System.Numerics.Vector4 _item831;
            private System.Numerics.Vector4 _item832;
            private System.Numerics.Vector4 _item833;
            private System.Numerics.Vector4 _item834;
            private System.Numerics.Vector4 _item835;
            private System.Numerics.Vector4 _item836;
            private System.Numerics.Vector4 _item837;
            private System.Numerics.Vector4 _item838;
            private System.Numerics.Vector4 _item839;
            private System.Numerics.Vector4 _item840;
            private System.Numerics.Vector4 _item841;
            private System.Numerics.Vector4 _item842;
            private System.Numerics.Vector4 _item843;
            private System.Numerics.Vector4 _item844;
            private System.Numerics.Vector4 _item845;
            private System.Numerics.Vector4 _item846;
            private System.Numerics.Vector4 _item847;
            private System.Numerics.Vector4 _item848;
            private System.Numerics.Vector4 _item849;
            private System.Numerics.Vector4 _item850;
            private System.Numerics.Vector4 _item851;
            private System.Numerics.Vector4 _item852;
            private System.Numerics.Vector4 _item853;
            private System.Numerics.Vector4 _item854;
            private System.Numerics.Vector4 _item855;
            private System.Numerics.Vector4 _item856;
            private System.Numerics.Vector4 _item857;
            private System.Numerics.Vector4 _item858;
            private System.Numerics.Vector4 _item859;
            private System.Numerics.Vector4 _item860;
            private System.Numerics.Vector4 _item861;
            private System.Numerics.Vector4 _item862;
            private System.Numerics.Vector4 _item863;
            private System.Numerics.Vector4 _item864;
            private System.Numerics.Vector4 _item865;
            private System.Numerics.Vector4 _item866;
            private System.Numerics.Vector4 _item867;
            private System.Numerics.Vector4 _item868;
            private System.Numerics.Vector4 _item869;
            private System.Numerics.Vector4 _item870;
            private System.Numerics.Vector4 _item871;
            private System.Numerics.Vector4 _item872;
            private System.Numerics.Vector4 _item873;
            private System.Numerics.Vector4 _item874;
            private System.Numerics.Vector4 _item875;
            private System.Numerics.Vector4 _item876;
            private System.Numerics.Vector4 _item877;
            private System.Numerics.Vector4 _item878;
            private System.Numerics.Vector4 _item879;
            private System.Numerics.Vector4 _item880;
            private System.Numerics.Vector4 _item881;
            private System.Numerics.Vector4 _item882;
            private System.Numerics.Vector4 _item883;
            private System.Numerics.Vector4 _item884;
            private System.Numerics.Vector4 _item885;
            private System.Numerics.Vector4 _item886;
            private System.Numerics.Vector4 _item887;
            private System.Numerics.Vector4 _item888;
            private System.Numerics.Vector4 _item889;
            private System.Numerics.Vector4 _item890;
            private System.Numerics.Vector4 _item891;
            private System.Numerics.Vector4 _item892;
            private System.Numerics.Vector4 _item893;
            private System.Numerics.Vector4 _item894;
            private System.Numerics.Vector4 _item895;
            private System.Numerics.Vector4 _item896;
            private System.Numerics.Vector4 _item897;
            private System.Numerics.Vector4 _item898;
            private System.Numerics.Vector4 _item899;
            private System.Numerics.Vector4 _item900;
            private System.Numerics.Vector4 _item901;
            private System.Numerics.Vector4 _item902;
            private System.Numerics.Vector4 _item903;
            private System.Numerics.Vector4 _item904;
            private System.Numerics.Vector4 _item905;
            private System.Numerics.Vector4 _item906;
            private System.Numerics.Vector4 _item907;
            private System.Numerics.Vector4 _item908;
            private System.Numerics.Vector4 _item909;
            private System.Numerics.Vector4 _item910;
            private System.Numerics.Vector4 _item911;
            private System.Numerics.Vector4 _item912;
            private System.Numerics.Vector4 _item913;
            private System.Numerics.Vector4 _item914;
            private System.Numerics.Vector4 _item915;
            private System.Numerics.Vector4 _item916;
            private System.Numerics.Vector4 _item917;
            private System.Numerics.Vector4 _item918;
            private System.Numerics.Vector4 _item919;
            private System.Numerics.Vector4 _item920;
            private System.Numerics.Vector4 _item921;
            private System.Numerics.Vector4 _item922;
            private System.Numerics.Vector4 _item923;
            private System.Numerics.Vector4 _item924;
            private System.Numerics.Vector4 _item925;
            private System.Numerics.Vector4 _item926;
            private System.Numerics.Vector4 _item927;
            private System.Numerics.Vector4 _item928;
            private System.Numerics.Vector4 _item929;
            private System.Numerics.Vector4 _item930;
            private System.Numerics.Vector4 _item931;
            private System.Numerics.Vector4 _item932;
            private System.Numerics.Vector4 _item933;
            private System.Numerics.Vector4 _item934;
            private System.Numerics.Vector4 _item935;
            private System.Numerics.Vector4 _item936;
            private System.Numerics.Vector4 _item937;
            private System.Numerics.Vector4 _item938;
            private System.Numerics.Vector4 _item939;
            private System.Numerics.Vector4 _item940;
            private System.Numerics.Vector4 _item941;
            private System.Numerics.Vector4 _item942;
            private System.Numerics.Vector4 _item943;
            private System.Numerics.Vector4 _item944;
            private System.Numerics.Vector4 _item945;
            private System.Numerics.Vector4 _item946;
            private System.Numerics.Vector4 _item947;
            private System.Numerics.Vector4 _item948;
            private System.Numerics.Vector4 _item949;
            private System.Numerics.Vector4 _item950;
            private System.Numerics.Vector4 _item951;
            private System.Numerics.Vector4 _item952;
            private System.Numerics.Vector4 _item953;
            private System.Numerics.Vector4 _item954;
            private System.Numerics.Vector4 _item955;
            private System.Numerics.Vector4 _item956;
            private System.Numerics.Vector4 _item957;
            private System.Numerics.Vector4 _item958;
            private System.Numerics.Vector4 _item959;
            private System.Numerics.Vector4 _item960;
            private System.Numerics.Vector4 _item961;
            private System.Numerics.Vector4 _item962;
            private System.Numerics.Vector4 _item963;
            private System.Numerics.Vector4 _item964;
            private System.Numerics.Vector4 _item965;
            private System.Numerics.Vector4 _item966;
            private System.Numerics.Vector4 _item967;
            private System.Numerics.Vector4 _item968;
            private System.Numerics.Vector4 _item969;
            private System.Numerics.Vector4 _item970;
            private System.Numerics.Vector4 _item971;
            private System.Numerics.Vector4 _item972;
            private System.Numerics.Vector4 _item973;
            private System.Numerics.Vector4 _item974;
            private System.Numerics.Vector4 _item975;
            private System.Numerics.Vector4 _item976;
            private System.Numerics.Vector4 _item977;
            private System.Numerics.Vector4 _item978;
            private System.Numerics.Vector4 _item979;
            private System.Numerics.Vector4 _item980;
            private System.Numerics.Vector4 _item981;
            private System.Numerics.Vector4 _item982;
            private System.Numerics.Vector4 _item983;
            private System.Numerics.Vector4 _item984;
            private System.Numerics.Vector4 _item985;
            private System.Numerics.Vector4 _item986;
            private System.Numerics.Vector4 _item987;
            private System.Numerics.Vector4 _item988;
            private System.Numerics.Vector4 _item989;
            private System.Numerics.Vector4 _item990;
            private System.Numerics.Vector4 _item991;
            private System.Numerics.Vector4 _item992;
            private System.Numerics.Vector4 _item993;
            private System.Numerics.Vector4 _item994;
            private System.Numerics.Vector4 _item995;
            private System.Numerics.Vector4 _item996;
            private System.Numerics.Vector4 _item997;
            private System.Numerics.Vector4 _item998;
            private System.Numerics.Vector4 _item999;
            private System.Numerics.Vector4 _item1000;
            private System.Numerics.Vector4 _item1001;
            private System.Numerics.Vector4 _item1002;
            private System.Numerics.Vector4 _item1003;
            private System.Numerics.Vector4 _item1004;
            private System.Numerics.Vector4 _item1005;
            private System.Numerics.Vector4 _item1006;
            private System.Numerics.Vector4 _item1007;
            private System.Numerics.Vector4 _item1008;
            private System.Numerics.Vector4 _item1009;
            private System.Numerics.Vector4 _item1010;
            private System.Numerics.Vector4 _item1011;
            private System.Numerics.Vector4 _item1012;
            private System.Numerics.Vector4 _item1013;
            private System.Numerics.Vector4 _item1014;
            private System.Numerics.Vector4 _item1015;
            private System.Numerics.Vector4 _item1016;
            private System.Numerics.Vector4 _item1017;
            private System.Numerics.Vector4 _item1018;
            private System.Numerics.Vector4 _item1019;
            private System.Numerics.Vector4 _item1020;
            private System.Numerics.Vector4 _item1021;
            private System.Numerics.Vector4 _item1022;
            private System.Numerics.Vector4 _item1023;
        }
        #pragma warning restore 169
        public lights_dataCollection lights_data;
    };
    /*
        #include <metal_stdlib>
        #include <simd/simd.h>

        using namespace metal;

        struct phong_vs_params
        {
            float4x4 mvp;
            float4x4 model;
        };

        struct main0_out
        {
            float3 world_normal [[user(locn0)]];
            float3 world_pos [[user(locn1)]];
            float4 base_color [[user(locn2)]];
            float4 gl_Position [[position]];
        };

        struct main0_in
        {
            float4 in_pos [[attribute(0)]];
            float3 in_normal [[attribute(1)]];
            float4 in_color [[attribute(3)]];
        };

        vertex main0_out main0(main0_in in [[stage_in]], constant phong_vs_params& _19 [[buffer(0)]])
        {
            main0_out out = {};
            out.gl_Position = _19.mvp * in.in_pos;
            out.world_normal = float3x3(float3(_19.model[0].xyz), float3(_19.model[1].xyz), float3(_19.model[2].xyz)) * in.in_normal;
            out.world_pos = (_19.model * in.in_pos).xyz;
            out.base_color = in.in_color;
            return out;
        }

    */
    static readonly byte[] phong_vs_source_metal_macos = {
            0x23,    0x69,    0x6e,    0x63,    0x6c,    0x75,    0x64,    0x65,    0x20,    0x3c,    0x6d,    0x65,    0x74,    0x61,    0x6c,    0x5f,    
            0x73,    0x74,    0x64,    0x6c,    0x69,    0x62,    0x3e,    0x0a,    0x23,    0x69,    0x6e,    0x63,    0x6c,    0x75,    0x64,    0x65,    
            0x20,    0x3c,    0x73,    0x69,    0x6d,    0x64,    0x2f,    0x73,    0x69,    0x6d,    0x64,    0x2e,    0x68,    0x3e,    0x0a,    0x0a,    
            0x75,    0x73,    0x69,    0x6e,    0x67,    0x20,    0x6e,    0x61,    0x6d,    0x65,    0x73,    0x70,    0x61,    0x63,    0x65,    0x20,    
            0x6d,    0x65,    0x74,    0x61,    0x6c,    0x3b,    0x0a,    0x0a,    0x73,    0x74,    0x72,    0x75,    0x63,    0x74,    0x20,    0x70,    
            0x68,    0x6f,    0x6e,    0x67,    0x5f,    0x76,    0x73,    0x5f,    0x70,    0x61,    0x72,    0x61,    0x6d,    0x73,    0x0a,    0x7b,    
            0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x34,    0x78,    0x34,    0x20,    0x6d,    0x76,    
            0x70,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x34,    0x78,    0x34,    0x20,    
            0x6d,    0x6f,    0x64,    0x65,    0x6c,    0x3b,    0x0a,    0x7d,    0x3b,    0x0a,    0x0a,    0x73,    0x74,    0x72,    0x75,    0x63,    
            0x74,    0x20,    0x6d,    0x61,    0x69,    0x6e,    0x30,    0x5f,    0x6f,    0x75,    0x74,    0x0a,    0x7b,    0x0a,    0x20,    0x20,    
            0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x33,    0x20,    0x77,    0x6f,    0x72,    0x6c,    0x64,    0x5f,    0x6e,    
            0x6f,    0x72,    0x6d,    0x61,    0x6c,    0x20,    0x5b,    0x5b,    0x75,    0x73,    0x65,    0x72,    0x28,    0x6c,    0x6f,    0x63,    
            0x6e,    0x30,    0x29,    0x5d,    0x5d,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    
            0x33,    0x20,    0x77,    0x6f,    0x72,    0x6c,    0x64,    0x5f,    0x70,    0x6f,    0x73,    0x20,    0x5b,    0x5b,    0x75,    0x73,    
            0x65,    0x72,    0x28,    0x6c,    0x6f,    0x63,    0x6e,    0x31,    0x29,    0x5d,    0x5d,    0x3b,    0x0a,    0x20,    0x20,    0x20,    
            0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x34,    0x20,    0x62,    0x61,    0x73,    0x65,    0x5f,    0x63,    0x6f,    0x6c,    
            0x6f,    0x72,    0x20,    0x5b,    0x5b,    0x75,    0x73,    0x65,    0x72,    0x28,    0x6c,    0x6f,    0x63,    0x6e,    0x32,    0x29,    
            0x5d,    0x5d,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x34,    0x20,    0x67,    
            0x6c,    0x5f,    0x50,    0x6f,    0x73,    0x69,    0x74,    0x69,    0x6f,    0x6e,    0x20,    0x5b,    0x5b,    0x70,    0x6f,    0x73,    
            0x69,    0x74,    0x69,    0x6f,    0x6e,    0x5d,    0x5d,    0x3b,    0x0a,    0x7d,    0x3b,    0x0a,    0x0a,    0x73,    0x74,    0x72,    
            0x75,    0x63,    0x74,    0x20,    0x6d,    0x61,    0x69,    0x6e,    0x30,    0x5f,    0x69,    0x6e,    0x0a,    0x7b,    0x0a,    0x20,    
            0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x34,    0x20,    0x69,    0x6e,    0x5f,    0x70,    0x6f,    0x73,    
            0x20,    0x5b,    0x5b,    0x61,    0x74,    0x74,    0x72,    0x69,    0x62,    0x75,    0x74,    0x65,    0x28,    0x30,    0x29,    0x5d,    
            0x5d,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x33,    0x20,    0x69,    0x6e,    
            0x5f,    0x6e,    0x6f,    0x72,    0x6d,    0x61,    0x6c,    0x20,    0x5b,    0x5b,    0x61,    0x74,    0x74,    0x72,    0x69,    0x62,    
            0x75,    0x74,    0x65,    0x28,    0x31,    0x29,    0x5d,    0x5d,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    
            0x6f,    0x61,    0x74,    0x34,    0x20,    0x69,    0x6e,    0x5f,    0x63,    0x6f,    0x6c,    0x6f,    0x72,    0x20,    0x5b,    0x5b,    
            0x61,    0x74,    0x74,    0x72,    0x69,    0x62,    0x75,    0x74,    0x65,    0x28,    0x33,    0x29,    0x5d,    0x5d,    0x3b,    0x0a,    
            0x7d,    0x3b,    0x0a,    0x0a,    0x76,    0x65,    0x72,    0x74,    0x65,    0x78,    0x20,    0x6d,    0x61,    0x69,    0x6e,    0x30,    
            0x5f,    0x6f,    0x75,    0x74,    0x20,    0x6d,    0x61,    0x69,    0x6e,    0x30,    0x28,    0x6d,    0x61,    0x69,    0x6e,    0x30,    
            0x5f,    0x69,    0x6e,    0x20,    0x69,    0x6e,    0x20,    0x5b,    0x5b,    0x73,    0x74,    0x61,    0x67,    0x65,    0x5f,    0x69,    
            0x6e,    0x5d,    0x5d,    0x2c,    0x20,    0x63,    0x6f,    0x6e,    0x73,    0x74,    0x61,    0x6e,    0x74,    0x20,    0x70,    0x68,    
            0x6f,    0x6e,    0x67,    0x5f,    0x76,    0x73,    0x5f,    0x70,    0x61,    0x72,    0x61,    0x6d,    0x73,    0x26,    0x20,    0x5f,    
            0x31,    0x39,    0x20,    0x5b,    0x5b,    0x62,    0x75,    0x66,    0x66,    0x65,    0x72,    0x28,    0x30,    0x29,    0x5d,    0x5d,    
            0x29,    0x0a,    0x7b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x6d,    0x61,    0x69,    0x6e,    0x30,    0x5f,    0x6f,    0x75,    
            0x74,    0x20,    0x6f,    0x75,    0x74,    0x20,    0x3d,    0x20,    0x7b,    0x7d,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    
            0x6f,    0x75,    0x74,    0x2e,    0x67,    0x6c,    0x5f,    0x50,    0x6f,    0x73,    0x69,    0x74,    0x69,    0x6f,    0x6e,    0x20,    
            0x3d,    0x20,    0x5f,    0x31,    0x39,    0x2e,    0x6d,    0x76,    0x70,    0x20,    0x2a,    0x20,    0x69,    0x6e,    0x2e,    0x69,    
            0x6e,    0x5f,    0x70,    0x6f,    0x73,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x6f,    0x75,    0x74,    0x2e,    0x77,    
            0x6f,    0x72,    0x6c,    0x64,    0x5f,    0x6e,    0x6f,    0x72,    0x6d,    0x61,    0x6c,    0x20,    0x3d,    0x20,    0x66,    0x6c,    
            0x6f,    0x61,    0x74,    0x33,    0x78,    0x33,    0x28,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x33,    0x28,    0x5f,    0x31,    
            0x39,    0x2e,    0x6d,    0x6f,    0x64,    0x65,    0x6c,    0x5b,    0x30,    0x5d,    0x2e,    0x78,    0x79,    0x7a,    0x29,    0x2c,    
            0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x33,    0x28,    0x5f,    0x31,    0x39,    0x2e,    0x6d,    0x6f,    0x64,    0x65,    
            0x6c,    0x5b,    0x31,    0x5d,    0x2e,    0x78,    0x79,    0x7a,    0x29,    0x2c,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    
            0x33,    0x28,    0x5f,    0x31,    0x39,    0x2e,    0x6d,    0x6f,    0x64,    0x65,    0x6c,    0x5b,    0x32,    0x5d,    0x2e,    0x78,    
            0x79,    0x7a,    0x29,    0x29,    0x20,    0x2a,    0x20,    0x69,    0x6e,    0x2e,    0x69,    0x6e,    0x5f,    0x6e,    0x6f,    0x72,    
            0x6d,    0x61,    0x6c,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x6f,    0x75,    0x74,    0x2e,    0x77,    0x6f,    0x72,    
            0x6c,    0x64,    0x5f,    0x70,    0x6f,    0x73,    0x20,    0x3d,    0x20,    0x28,    0x5f,    0x31,    0x39,    0x2e,    0x6d,    0x6f,    
            0x64,    0x65,    0x6c,    0x20,    0x2a,    0x20,    0x69,    0x6e,    0x2e,    0x69,    0x6e,    0x5f,    0x70,    0x6f,    0x73,    0x29,    
            0x2e,    0x78,    0x79,    0x7a,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x6f,    0x75,    0x74,    0x2e,    0x62,    0x61,    
            0x73,    0x65,    0x5f,    0x63,    0x6f,    0x6c,    0x6f,    0x72,    0x20,    0x3d,    0x20,    0x69,    0x6e,    0x2e,    0x69,    0x6e,    
            0x5f,    0x63,    0x6f,    0x6c,    0x6f,    0x72,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x72,    0x65,    0x74,    0x75,    
            0x72,    0x6e,    0x20,    0x6f,    0x75,    0x74,    0x3b,    0x0a,    0x7d,    0x0a,    0x0a,    0x00,    
};
    /*
        #include <metal_stdlib>
        #include <simd/simd.h>

        using namespace metal;

        struct phong_fs_params
        {
            float4 ambient_and_count;
            float4 lights_data[1024];
        };

        struct main0_out
        {
            float4 frag_color [[color(0)]];
        };

        struct main0_in
        {
            float3 world_normal [[user(locn0)]];
            float3 world_pos [[user(locn1)]];
            float4 base_color [[user(locn2)]];
        };

        fragment main0_out main0(main0_in in [[stage_in]], constant phong_fs_params& _21 [[buffer(1)]])
        {
            main0_out out = {};
            float3 _13 = fast::normalize(in.world_normal);
            float3 accum = _21.ambient_and_count.xyz;
            int _36 = min(int(_21.ambient_and_count.w), 256);
            for (int i = 0; i < _36; i++)
            {
                int _52 = i * 4;
                int _59 = _52 + 1;
                int _66 = _52 + 2;
                int _73 = _52 + 3;
                float3 _82 = _21.lights_data[_66].xyz * _21.lights_data[_66].w;
                int _86 = int(_21.lights_data[_52].w);
                if (_86 == 0)
                {
                    accum += (_82 * fast::max(dot(_13, fast::normalize(-_21.lights_data[_52].xyz)), 0.0));
                }
                else
                {
                    if (_86 == 1)
                    {
                        float3 _115 = _21.lights_data[_52].xyz - in.world_pos;
                        float _118 = length(_115);
                        if ((_118 < _21.lights_data[_59].w) && (_21.lights_data[_59].w > 0.0))
                        {
                            float _136 = _118 / _21.lights_data[_59].w;
                            accum += ((_82 * fast::max(dot(_13, fast::normalize(_115)), 0.0)) * fast::max(1.0 - (_136 * _136), 0.0));
                        }
                    }
                    else
                    {
                        float3 _159 = _21.lights_data[_52].xyz - in.world_pos;
                        float _162 = length(_159);
                        if ((_162 < _21.lights_data[_59].w) && (_21.lights_data[_59].w > 0.0))
                        {
                            float3 _176 = fast::normalize(_159);
                            float _180 = _162 / _21.lights_data[_59].w;
                            accum += (((_82 * fast::max(dot(_13, _176), 0.0)) * fast::max(1.0 - (_180 * _180), 0.0)) * fast::clamp((dot(-_176, fast::normalize(_21.lights_data[_59].xyz)) - _21.lights_data[_73].y) / fast::max(_21.lights_data[_73].x - _21.lights_data[_73].y, 9.9999997473787516355514526367188e-05), 0.0, 1.0));
                        }
                    }
                }
            }
            out.frag_color = float4(in.base_color.xyz * accum, in.base_color.w);
            return out;
        }

    */
    static readonly byte[] phong_fs_source_metal_macos = {
            0x23,    0x69,    0x6e,    0x63,    0x6c,    0x75,    0x64,    0x65,    0x20,    0x3c,    0x6d,    0x65,    0x74,    0x61,    0x6c,    0x5f,    
            0x73,    0x74,    0x64,    0x6c,    0x69,    0x62,    0x3e,    0x0a,    0x23,    0x69,    0x6e,    0x63,    0x6c,    0x75,    0x64,    0x65,    
            0x20,    0x3c,    0x73,    0x69,    0x6d,    0x64,    0x2f,    0x73,    0x69,    0x6d,    0x64,    0x2e,    0x68,    0x3e,    0x0a,    0x0a,    
            0x75,    0x73,    0x69,    0x6e,    0x67,    0x20,    0x6e,    0x61,    0x6d,    0x65,    0x73,    0x70,    0x61,    0x63,    0x65,    0x20,    
            0x6d,    0x65,    0x74,    0x61,    0x6c,    0x3b,    0x0a,    0x0a,    0x73,    0x74,    0x72,    0x75,    0x63,    0x74,    0x20,    0x70,    
            0x68,    0x6f,    0x6e,    0x67,    0x5f,    0x66,    0x73,    0x5f,    0x70,    0x61,    0x72,    0x61,    0x6d,    0x73,    0x0a,    0x7b,    
            0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x34,    0x20,    0x61,    0x6d,    0x62,    0x69,    
            0x65,    0x6e,    0x74,    0x5f,    0x61,    0x6e,    0x64,    0x5f,    0x63,    0x6f,    0x75,    0x6e,    0x74,    0x3b,    0x0a,    0x20,    
            0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x34,    0x20,    0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    
            0x5f,    0x64,    0x61,    0x74,    0x61,    0x5b,    0x31,    0x30,    0x32,    0x34,    0x5d,    0x3b,    0x0a,    0x7d,    0x3b,    0x0a,    
            0x0a,    0x73,    0x74,    0x72,    0x75,    0x63,    0x74,    0x20,    0x6d,    0x61,    0x69,    0x6e,    0x30,    0x5f,    0x6f,    0x75,    
            0x74,    0x0a,    0x7b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x34,    0x20,    0x66,    
            0x72,    0x61,    0x67,    0x5f,    0x63,    0x6f,    0x6c,    0x6f,    0x72,    0x20,    0x5b,    0x5b,    0x63,    0x6f,    0x6c,    0x6f,    
            0x72,    0x28,    0x30,    0x29,    0x5d,    0x5d,    0x3b,    0x0a,    0x7d,    0x3b,    0x0a,    0x0a,    0x73,    0x74,    0x72,    0x75,    
            0x63,    0x74,    0x20,    0x6d,    0x61,    0x69,    0x6e,    0x30,    0x5f,    0x69,    0x6e,    0x0a,    0x7b,    0x0a,    0x20,    0x20,    
            0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x33,    0x20,    0x77,    0x6f,    0x72,    0x6c,    0x64,    0x5f,    0x6e,    
            0x6f,    0x72,    0x6d,    0x61,    0x6c,    0x20,    0x5b,    0x5b,    0x75,    0x73,    0x65,    0x72,    0x28,    0x6c,    0x6f,    0x63,    
            0x6e,    0x30,    0x29,    0x5d,    0x5d,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    
            0x33,    0x20,    0x77,    0x6f,    0x72,    0x6c,    0x64,    0x5f,    0x70,    0x6f,    0x73,    0x20,    0x5b,    0x5b,    0x75,    0x73,    
            0x65,    0x72,    0x28,    0x6c,    0x6f,    0x63,    0x6e,    0x31,    0x29,    0x5d,    0x5d,    0x3b,    0x0a,    0x20,    0x20,    0x20,    
            0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x34,    0x20,    0x62,    0x61,    0x73,    0x65,    0x5f,    0x63,    0x6f,    0x6c,    
            0x6f,    0x72,    0x20,    0x5b,    0x5b,    0x75,    0x73,    0x65,    0x72,    0x28,    0x6c,    0x6f,    0x63,    0x6e,    0x32,    0x29,    
            0x5d,    0x5d,    0x3b,    0x0a,    0x7d,    0x3b,    0x0a,    0x0a,    0x66,    0x72,    0x61,    0x67,    0x6d,    0x65,    0x6e,    0x74,    
            0x20,    0x6d,    0x61,    0x69,    0x6e,    0x30,    0x5f,    0x6f,    0x75,    0x74,    0x20,    0x6d,    0x61,    0x69,    0x6e,    0x30,    
            0x28,    0x6d,    0x61,    0x69,    0x6e,    0x30,    0x5f,    0x69,    0x6e,    0x20,    0x69,    0x6e,    0x20,    0x5b,    0x5b,    0x73,    
            0x74,    0x61,    0x67,    0x65,    0x5f,    0x69,    0x6e,    0x5d,    0x5d,    0x2c,    0x20,    0x63,    0x6f,    0x6e,    0x73,    0x74,    
            0x61,    0x6e,    0x74,    0x20,    0x70,    0x68,    0x6f,    0x6e,    0x67,    0x5f,    0x66,    0x73,    0x5f,    0x70,    0x61,    0x72,    
            0x61,    0x6d,    0x73,    0x26,    0x20,    0x5f,    0x32,    0x31,    0x20,    0x5b,    0x5b,    0x62,    0x75,    0x66,    0x66,    0x65,    
            0x72,    0x28,    0x31,    0x29,    0x5d,    0x5d,    0x29,    0x0a,    0x7b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x6d,    0x61,    
            0x69,    0x6e,    0x30,    0x5f,    0x6f,    0x75,    0x74,    0x20,    0x6f,    0x75,    0x74,    0x20,    0x3d,    0x20,    0x7b,    0x7d,    
            0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x33,    0x20,    0x5f,    0x31,    0x33,    
            0x20,    0x3d,    0x20,    0x66,    0x61,    0x73,    0x74,    0x3a,    0x3a,    0x6e,    0x6f,    0x72,    0x6d,    0x61,    0x6c,    0x69,    
            0x7a,    0x65,    0x28,    0x69,    0x6e,    0x2e,    0x77,    0x6f,    0x72,    0x6c,    0x64,    0x5f,    0x6e,    0x6f,    0x72,    0x6d,    
            0x61,    0x6c,    0x29,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x33,    0x20,    
            0x61,    0x63,    0x63,    0x75,    0x6d,    0x20,    0x3d,    0x20,    0x5f,    0x32,    0x31,    0x2e,    0x61,    0x6d,    0x62,    0x69,    
            0x65,    0x6e,    0x74,    0x5f,    0x61,    0x6e,    0x64,    0x5f,    0x63,    0x6f,    0x75,    0x6e,    0x74,    0x2e,    0x78,    0x79,    
            0x7a,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x69,    0x6e,    0x74,    0x20,    0x5f,    0x33,    0x36,    0x20,    0x3d,    
            0x20,    0x6d,    0x69,    0x6e,    0x28,    0x69,    0x6e,    0x74,    0x28,    0x5f,    0x32,    0x31,    0x2e,    0x61,    0x6d,    0x62,    
            0x69,    0x65,    0x6e,    0x74,    0x5f,    0x61,    0x6e,    0x64,    0x5f,    0x63,    0x6f,    0x75,    0x6e,    0x74,    0x2e,    0x77,    
            0x29,    0x2c,    0x20,    0x32,    0x35,    0x36,    0x29,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6f,    0x72,    
            0x20,    0x28,    0x69,    0x6e,    0x74,    0x20,    0x69,    0x20,    0x3d,    0x20,    0x30,    0x3b,    0x20,    0x69,    0x20,    0x3c,    
            0x20,    0x5f,    0x33,    0x36,    0x3b,    0x20,    0x69,    0x2b,    0x2b,    0x29,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x7b,    
            0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x69,    0x6e,    0x74,    0x20,    0x5f,    0x35,    0x32,    
            0x20,    0x3d,    0x20,    0x69,    0x20,    0x2a,    0x20,    0x34,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x69,    0x6e,    0x74,    0x20,    0x5f,    0x35,    0x39,    0x20,    0x3d,    0x20,    0x5f,    0x35,    0x32,    0x20,    
            0x2b,    0x20,    0x31,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x69,    0x6e,    0x74,    
            0x20,    0x5f,    0x36,    0x36,    0x20,    0x3d,    0x20,    0x5f,    0x35,    0x32,    0x20,    0x2b,    0x20,    0x32,    0x3b,    0x0a,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x69,    0x6e,    0x74,    0x20,    0x5f,    0x37,    0x33,    0x20,    
            0x3d,    0x20,    0x5f,    0x35,    0x32,    0x20,    0x2b,    0x20,    0x33,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x33,    0x20,    0x5f,    0x38,    0x32,    0x20,    0x3d,    0x20,    
            0x5f,    0x32,    0x31,    0x2e,    0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    0x61,    0x5b,    
            0x5f,    0x36,    0x36,    0x5d,    0x2e,    0x78,    0x79,    0x7a,    0x20,    0x2a,    0x20,    0x5f,    0x32,    0x31,    0x2e,    0x6c,    
            0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    0x61,    0x5b,    0x5f,    0x36,    0x36,    0x5d,    0x2e,    
            0x77,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x69,    0x6e,    0x74,    0x20,    0x5f,    
            0x38,    0x36,    0x20,    0x3d,    0x20,    0x69,    0x6e,    0x74,    0x28,    0x5f,    0x32,    0x31,    0x2e,    0x6c,    0x69,    0x67,    
            0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    0x61,    0x5b,    0x5f,    0x35,    0x32,    0x5d,    0x2e,    0x77,    0x29,    
            0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x69,    0x66,    0x20,    0x28,    0x5f,    0x38,    
            0x36,    0x20,    0x3d,    0x3d,    0x20,    0x30,    0x29,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x7b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x61,    0x63,    
            0x63,    0x75,    0x6d,    0x20,    0x2b,    0x3d,    0x20,    0x28,    0x5f,    0x38,    0x32,    0x20,    0x2a,    0x20,    0x66,    0x61,    
            0x73,    0x74,    0x3a,    0x3a,    0x6d,    0x61,    0x78,    0x28,    0x64,    0x6f,    0x74,    0x28,    0x5f,    0x31,    0x33,    0x2c,    
            0x20,    0x66,    0x61,    0x73,    0x74,    0x3a,    0x3a,    0x6e,    0x6f,    0x72,    0x6d,    0x61,    0x6c,    0x69,    0x7a,    0x65,    
            0x28,    0x2d,    0x5f,    0x32,    0x31,    0x2e,    0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    
            0x61,    0x5b,    0x5f,    0x35,    0x32,    0x5d,    0x2e,    0x78,    0x79,    0x7a,    0x29,    0x29,    0x2c,    0x20,    0x30,    0x2e,    
            0x30,    0x29,    0x29,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x7d,    0x0a,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x65,    0x6c,    0x73,    0x65,    0x0a,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x7b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x69,    0x66,    0x20,    0x28,    0x5f,    0x38,    0x36,    0x20,    0x3d,    0x3d,    0x20,    0x31,    0x29,    0x0a,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x7b,    0x0a,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    
            0x6f,    0x61,    0x74,    0x33,    0x20,    0x5f,    0x31,    0x31,    0x35,    0x20,    0x3d,    0x20,    0x5f,    0x32,    0x31,    0x2e,    
            0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    0x61,    0x5b,    0x5f,    0x35,    0x32,    0x5d,    
            0x2e,    0x78,    0x79,    0x7a,    0x20,    0x2d,    0x20,    0x69,    0x6e,    0x2e,    0x77,    0x6f,    0x72,    0x6c,    0x64,    0x5f,    
            0x70,    0x6f,    0x73,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x20,    0x5f,    0x31,    0x31,    0x38,    0x20,    
            0x3d,    0x20,    0x6c,    0x65,    0x6e,    0x67,    0x74,    0x68,    0x28,    0x5f,    0x31,    0x31,    0x35,    0x29,    0x3b,    0x0a,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x69,    0x66,    0x20,    0x28,    0x28,    0x5f,    0x31,    0x31,    0x38,    0x20,    0x3c,    0x20,    0x5f,    0x32,    0x31,    0x2e,    
            0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    0x61,    0x5b,    0x5f,    0x35,    0x39,    0x5d,    
            0x2e,    0x77,    0x29,    0x20,    0x26,    0x26,    0x20,    0x28,    0x5f,    0x32,    0x31,    0x2e,    0x6c,    0x69,    0x67,    0x68,    
            0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    0x61,    0x5b,    0x5f,    0x35,    0x39,    0x5d,    0x2e,    0x77,    0x20,    0x3e,    
            0x20,    0x30,    0x2e,    0x30,    0x29,    0x29,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x7b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    
            0x61,    0x74,    0x20,    0x5f,    0x31,    0x33,    0x36,    0x20,    0x3d,    0x20,    0x5f,    0x31,    0x31,    0x38,    0x20,    0x2f,    
            0x20,    0x5f,    0x32,    0x31,    0x2e,    0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    0x61,    
            0x5b,    0x5f,    0x35,    0x39,    0x5d,    0x2e,    0x77,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x61,    0x63,    0x63,    
            0x75,    0x6d,    0x20,    0x2b,    0x3d,    0x20,    0x28,    0x28,    0x5f,    0x38,    0x32,    0x20,    0x2a,    0x20,    0x66,    0x61,    
            0x73,    0x74,    0x3a,    0x3a,    0x6d,    0x61,    0x78,    0x28,    0x64,    0x6f,    0x74,    0x28,    0x5f,    0x31,    0x33,    0x2c,    
            0x20,    0x66,    0x61,    0x73,    0x74,    0x3a,    0x3a,    0x6e,    0x6f,    0x72,    0x6d,    0x61,    0x6c,    0x69,    0x7a,    0x65,    
            0x28,    0x5f,    0x31,    0x31,    0x35,    0x29,    0x29,    0x2c,    0x20,    0x30,    0x2e,    0x30,    0x29,    0x29,    0x20,    0x2a,    
            0x20,    0x66,    0x61,    0x73,    0x74,    0x3a,    0x3a,    0x6d,    0x61,    0x78,    0x28,    0x31,    0x2e,    0x30,    0x20,    0x2d,    
            0x20,    0x28,    0x5f,    0x31,    0x33,    0x36,    0x20,    0x2a,    0x20,    0x5f,    0x31,    0x33,    0x36,    0x29,    0x2c,    0x20,    
            0x30,    0x2e,    0x30,    0x29,    0x29,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x7d,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x7d,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x65,    0x6c,    0x73,    0x65,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x7b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x33,    0x20,    0x5f,    0x31,    0x35,    
            0x39,    0x20,    0x3d,    0x20,    0x5f,    0x32,    0x31,    0x2e,    0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    
            0x61,    0x74,    0x61,    0x5b,    0x5f,    0x35,    0x32,    0x5d,    0x2e,    0x78,    0x79,    0x7a,    0x20,    0x2d,    0x20,    0x69,    
            0x6e,    0x2e,    0x77,    0x6f,    0x72,    0x6c,    0x64,    0x5f,    0x70,    0x6f,    0x73,    0x3b,    0x0a,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    
            0x61,    0x74,    0x20,    0x5f,    0x31,    0x36,    0x32,    0x20,    0x3d,    0x20,    0x6c,    0x65,    0x6e,    0x67,    0x74,    0x68,    
            0x28,    0x5f,    0x31,    0x35,    0x39,    0x29,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x69,    0x66,    0x20,    0x28,    0x28,    0x5f,    0x31,    0x36,    
            0x32,    0x20,    0x3c,    0x20,    0x5f,    0x32,    0x31,    0x2e,    0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    
            0x61,    0x74,    0x61,    0x5b,    0x5f,    0x35,    0x39,    0x5d,    0x2e,    0x77,    0x29,    0x20,    0x26,    0x26,    0x20,    0x28,    
            0x5f,    0x32,    0x31,    0x2e,    0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    0x61,    0x5b,    
            0x5f,    0x35,    0x39,    0x5d,    0x2e,    0x77,    0x20,    0x3e,    0x20,    0x30,    0x2e,    0x30,    0x29,    0x29,    0x0a,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x7b,    
            0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    0x6f,    0x61,    0x74,    0x33,    0x20,    0x5f,    0x31,    0x37,    0x36,    
            0x20,    0x3d,    0x20,    0x66,    0x61,    0x73,    0x74,    0x3a,    0x3a,    0x6e,    0x6f,    0x72,    0x6d,    0x61,    0x6c,    0x69,    
            0x7a,    0x65,    0x28,    0x5f,    0x31,    0x35,    0x39,    0x29,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x66,    0x6c,    
            0x6f,    0x61,    0x74,    0x20,    0x5f,    0x31,    0x38,    0x30,    0x20,    0x3d,    0x20,    0x5f,    0x31,    0x36,    0x32,    0x20,    
            0x2f,    0x20,    0x5f,    0x32,    0x31,    0x2e,    0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    
            0x61,    0x5b,    0x5f,    0x35,    0x39,    0x5d,    0x2e,    0x77,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x61,    0x63,    
            0x63,    0x75,    0x6d,    0x20,    0x2b,    0x3d,    0x20,    0x28,    0x28,    0x28,    0x5f,    0x38,    0x32,    0x20,    0x2a,    0x20,    
            0x66,    0x61,    0x73,    0x74,    0x3a,    0x3a,    0x6d,    0x61,    0x78,    0x28,    0x64,    0x6f,    0x74,    0x28,    0x5f,    0x31,    
            0x33,    0x2c,    0x20,    0x5f,    0x31,    0x37,    0x36,    0x29,    0x2c,    0x20,    0x30,    0x2e,    0x30,    0x29,    0x29,    0x20,    
            0x2a,    0x20,    0x66,    0x61,    0x73,    0x74,    0x3a,    0x3a,    0x6d,    0x61,    0x78,    0x28,    0x31,    0x2e,    0x30,    0x20,    
            0x2d,    0x20,    0x28,    0x5f,    0x31,    0x38,    0x30,    0x20,    0x2a,    0x20,    0x5f,    0x31,    0x38,    0x30,    0x29,    0x2c,    
            0x20,    0x30,    0x2e,    0x30,    0x29,    0x29,    0x20,    0x2a,    0x20,    0x66,    0x61,    0x73,    0x74,    0x3a,    0x3a,    0x63,    
            0x6c,    0x61,    0x6d,    0x70,    0x28,    0x28,    0x64,    0x6f,    0x74,    0x28,    0x2d,    0x5f,    0x31,    0x37,    0x36,    0x2c,    
            0x20,    0x66,    0x61,    0x73,    0x74,    0x3a,    0x3a,    0x6e,    0x6f,    0x72,    0x6d,    0x61,    0x6c,    0x69,    0x7a,    0x65,    
            0x28,    0x5f,    0x32,    0x31,    0x2e,    0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    0x61,    
            0x5b,    0x5f,    0x35,    0x39,    0x5d,    0x2e,    0x78,    0x79,    0x7a,    0x29,    0x29,    0x20,    0x2d,    0x20,    0x5f,    0x32,    
            0x31,    0x2e,    0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    0x61,    0x5b,    0x5f,    0x37,    
            0x33,    0x5d,    0x2e,    0x79,    0x29,    0x20,    0x2f,    0x20,    0x66,    0x61,    0x73,    0x74,    0x3a,    0x3a,    0x6d,    0x61,    
            0x78,    0x28,    0x5f,    0x32,    0x31,    0x2e,    0x6c,    0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    
            0x61,    0x5b,    0x5f,    0x37,    0x33,    0x5d,    0x2e,    0x78,    0x20,    0x2d,    0x20,    0x5f,    0x32,    0x31,    0x2e,    0x6c,    
            0x69,    0x67,    0x68,    0x74,    0x73,    0x5f,    0x64,    0x61,    0x74,    0x61,    0x5b,    0x5f,    0x37,    0x33,    0x5d,    0x2e,    
            0x79,    0x2c,    0x20,    0x39,    0x2e,    0x39,    0x39,    0x39,    0x39,    0x39,    0x39,    0x37,    0x34,    0x37,    0x33,    0x37,    
            0x38,    0x37,    0x35,    0x31,    0x36,    0x33,    0x35,    0x35,    0x35,    0x31,    0x34,    0x35,    0x32,    0x36,    0x33,    0x36,    
            0x37,    0x31,    0x38,    0x38,    0x65,    0x2d,    0x30,    0x35,    0x29,    0x2c,    0x20,    0x30,    0x2e,    0x30,    0x2c,    0x20,    
            0x31,    0x2e,    0x30,    0x29,    0x29,    0x3b,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x7d,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    
            0x20,    0x20,    0x20,    0x20,    0x20,    0x7d,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x20,    0x7d,    
            0x0a,    0x20,    0x20,    0x20,    0x20,    0x7d,    0x0a,    0x20,    0x20,    0x20,    0x20,    0x6f,    0x75,    0x74,    0x2e,    0x66,    
            0x72,    0x61,    0x67,    0x5f,    0x63,    0x6f,    0x6c,    0x6f,    0x72,    0x20,    0x3d,    0x20,    0x66,    0x6c,    0x6f,    0x61,    
            0x74,    0x34,    0x28,    0x69,    0x6e,    0x2e,    0x62,    0x61,    0x73,    0x65,    0x5f,    0x63,    0x6f,    0x6c,    0x6f,    0x72,    
            0x2e,    0x78,    0x79,    0x7a,    0x20,    0x2a,    0x20,    0x61,    0x63,    0x63,    0x75,    0x6d,    0x2c,    0x20,    0x69,    0x6e,    
            0x2e,    0x62,    0x61,    0x73,    0x65,    0x5f,    0x63,    0x6f,    0x6c,    0x6f,    0x72,    0x2e,    0x77,    0x29,    0x3b,    0x0a,    
            0x20,    0x20,    0x20,    0x20,    0x72,    0x65,    0x74,    0x75,    0x72,    0x6e,    0x20,    0x6f,    0x75,    0x74,    0x3b,    0x0a,    
            0x7d,    0x0a,    0x0a,    0x00,    
};
    public static unsafe sg_shader_desc phong_shader_desc(sg_backend backend) {
        if (backend == SG_BACKEND_METAL_MACOS) {
            sg_shader_desc desc = default(sg_shader_desc);
            desc.vertex_func.source = System.Text.Encoding.UTF8.GetString(phong_vs_source_metal_macos);
            desc.vertex_func.entry = "main0";
            desc.fragment_func.source = System.Text.Encoding.UTF8.GetString(phong_fs_source_metal_macos);
            desc.fragment_func.entry = "main0";
            desc.attrs[0].base_type = SG_SHADERATTRBASETYPE_FLOAT;
            desc.attrs[1].base_type = SG_SHADERATTRBASETYPE_FLOAT;
            desc.attrs[2].base_type = SG_SHADERATTRBASETYPE_FLOAT;
            desc.attrs[3].base_type = SG_SHADERATTRBASETYPE_FLOAT;
            desc.uniform_blocks[0].stage = SG_SHADERSTAGE_VERTEX;
            desc.uniform_blocks[0].layout = SG_UNIFORMLAYOUT_STD140;
            desc.uniform_blocks[0].size = 128;
            desc.uniform_blocks[0].msl_buffer_n = 0;
            desc.uniform_blocks[1].stage = SG_SHADERSTAGE_FRAGMENT;
            desc.uniform_blocks[1].layout = SG_UNIFORMLAYOUT_STD140;
            desc.uniform_blocks[1].size = 16400;
            desc.uniform_blocks[1].msl_buffer_n = 1;
            desc.label = "phong_shader";
            return desc;
        }
        return default(sg_shader_desc);
    }
}

} // namescape 

