/*
    AUTO-GENERATED OZZUTIL INTERNAL WRAPPER FUNCTIONS
    This file is automatically generated by gen_csharp.py
    DO NOT EDIT MANUALLY

    WebAssembly/Emscripten cannot marshal structs returned by value through P/Invoke.
    These _internal helper functions work around this limitation by taking an output
    pointer parameter instead.
*/

#ifndef OZZUTIL_CSHARP_INTERNAL_WRAPPERS_H
#define OZZUTIL_CSHARP_INTERNAL_WRAPPERS_H

#include "ozzutil.h"

// For Emscripten builds, these functions need to be exported
#ifdef __EMSCRIPTEN__
    #include <emscripten.h>
    #define OZZUTIL_EXPORT EMSCRIPTEN_KEEPALIVE
#else
    #define OZZUTIL_EXPORT
#endif

// ========== OzzUtil (ozz_) ==========

OZZUTIL_EXPORT void ozz_joint_texture_internal(sg_image* result) {
    *result = ozz_joint_texture();
}

OZZUTIL_EXPORT void ozz_joint_texture_view_internal(sg_view* result) {
    *result = ozz_joint_texture_view();
}

OZZUTIL_EXPORT void ozz_joint_sampler_internal(sg_sampler* result) {
    *result = ozz_joint_sampler();
}

OZZUTIL_EXPORT void ozz_vertex_buffer_internal(sg_buffer* result, ozz_instance_t * ozz) {
    *result = ozz_vertex_buffer(ozz);
}

OZZUTIL_EXPORT void ozz_index_buffer_internal(sg_buffer* result, ozz_instance_t * ozz) {
    *result = ozz_index_buffer(ozz);
}

#endif // OZZUTIL_CSHARP_INTERNAL_WRAPPERS_H
