/******************************************************************************
 * Spine Runtimes Extension Implementation using Sokol
 * 
 * This file provides implementations of the extension functions required
 * by spine-c using sokol headers (without SOKOL_IMPL since this is a library).
 *****************************************************************************/

/* Include spine headers first - required by sokol_spine.h */
#include <spine/spine.h>

#ifdef __EMSCRIPTEN__
    #define SOKOL_GLES3
#elif defined(__APPLE__)
    #define SOKOL_METAL
#elif defined(_WIN32)
    #define SOKOL_D3D11
#elif defined(__ANDROID__)
    #define SOKOL_GLES3
#else
    #define SOKOL_GLCORE
#endif

#ifndef SOKOL_NO_ENTRY
    #define SOKOL_NO_ENTRY
#endif

#include "sokol_defines.h"


#include "sokol_gfx.h"

/* Now include sokol_spine.h which provides the extension implementations */
#define SOKOL_SPINE_IMPL
#include "util/sokol_spine.h"

/*=== C# BINDING HELPERS =====================================================
    WebAssembly/Emscripten cannot marshal structs returned by value through P/Invoke.
    These _internal helper functions work around this limitation by taking an output
    pointer parameter instead. The C# binding generator automatically creates wrappers
    that call these functions on WebAssembly builds while using the regular functions
    on other platforms.
    
    The internal wrapper functions are auto-generated by bindgen/gen_csharp.py
    and included from spine_c_csharp_internal_wrappers.h
============================================================================*/

// Include auto-generated internal wrapper functions for spine-c C# bindings
#include "spine_c_csharp_internal_wrappers.h"
