/*
    AUTO-GENERATED SPINE-C INTERNAL WRAPPER FUNCTIONS
    This file is automatically generated by gen_csharp.py
    DO NOT EDIT MANUALLY

    WebAssembly/Emscripten cannot marshal structs returned by value through P/Invoke.
    These _internal helper functions work around this limitation by taking an output
    pointer parameter instead.
*/

#ifndef SPINE_C_CSHARP_INTERNAL_WRAPPERS_H
#define SPINE_C_CSHARP_INTERNAL_WRAPPERS_H

#include <spine/spine.h>
#include "../sokol/util/sokol_spine.h"

// For Emscripten builds, these functions need to be exported
#ifdef __EMSCRIPTEN__
    #include <emscripten.h>
    #define SPINE_EXPORT EMSCRIPTEN_KEEPALIVE
#else
    #define SPINE_EXPORT
#endif

// ========== SSpine (sspine_) ==========

SPINE_EXPORT void sspine_make_context_internal(sspine_context* result, const sspine_context_desc * desc) {
    *result = sspine_make_context(desc);
}

SPINE_EXPORT void sspine_get_context_internal(sspine_context* result) {
    *result = sspine_get_context();
}

SPINE_EXPORT void sspine_default_context_internal(sspine_context* result) {
    *result = sspine_default_context();
}

SPINE_EXPORT void sspine_get_context_info_internal(sspine_context_info* result, sspine_context ctx) {
    *result = sspine_get_context_info(ctx);
}

SPINE_EXPORT void sspine_make_atlas_internal(sspine_atlas* result, const sspine_atlas_desc * desc) {
    *result = sspine_make_atlas(desc);
}

SPINE_EXPORT void sspine_make_skeleton_internal(sspine_skeleton* result, const sspine_skeleton_desc * desc) {
    *result = sspine_make_skeleton(desc);
}

SPINE_EXPORT void sspine_make_skinset_internal(sspine_skinset* result, const sspine_skinset_desc * desc) {
    *result = sspine_make_skinset(desc);
}

SPINE_EXPORT void sspine_make_instance_internal(sspine_instance* result, const sspine_instance_desc * desc) {
    *result = sspine_make_instance(desc);
}

SPINE_EXPORT void sspine_get_triggered_event_info_internal(sspine_triggered_event_info* result, sspine_instance instance, int triggered_event_index) {
    *result = sspine_get_triggered_event_info(instance, triggered_event_index);
}

SPINE_EXPORT void sspine_layer_transform_to_mat4_internal(sspine_mat4* result, const sspine_layer_transform * tform) {
    *result = sspine_layer_transform_to_mat4(tform);
}

SPINE_EXPORT void sspine_get_skeleton_atlas_internal(sspine_atlas* result, sspine_skeleton skeleton) {
    *result = sspine_get_skeleton_atlas(skeleton);
}

SPINE_EXPORT void sspine_get_instance_skeleton_internal(sspine_skeleton* result, sspine_instance instance) {
    *result = sspine_get_instance_skeleton(instance);
}

SPINE_EXPORT void sspine_image_by_index_internal(sspine_image* result, sspine_atlas atlas, int index) {
    *result = sspine_image_by_index(atlas, index);
}

SPINE_EXPORT void sspine_get_image_info_internal(sspine_image_info* result, sspine_image image) {
    *result = sspine_get_image_info(image);
}

SPINE_EXPORT void sspine_atlas_page_by_index_internal(sspine_atlas_page* result, sspine_atlas atlas, int index) {
    *result = sspine_atlas_page_by_index(atlas, index);
}

SPINE_EXPORT void sspine_get_atlas_page_info_internal(sspine_atlas_page_info* result, sspine_atlas_page page) {
    *result = sspine_get_atlas_page_info(page);
}

SPINE_EXPORT void sspine_get_position_internal(sspine_vec2* result, sspine_instance instance) {
    *result = sspine_get_position(instance);
}

SPINE_EXPORT void sspine_get_scale_internal(sspine_vec2* result, sspine_instance instance) {
    *result = sspine_get_scale(instance);
}

SPINE_EXPORT void sspine_anim_by_name_internal(sspine_anim* result, sspine_skeleton skeleton, const char * name) {
    *result = sspine_anim_by_name(skeleton, name);
}

SPINE_EXPORT void sspine_anim_by_index_internal(sspine_anim* result, sspine_skeleton skeleton, int index) {
    *result = sspine_anim_by_index(skeleton, index);
}

SPINE_EXPORT void sspine_get_anim_info_internal(sspine_anim_info* result, sspine_anim anim) {
    *result = sspine_get_anim_info(anim);
}

SPINE_EXPORT void sspine_bone_by_name_internal(sspine_bone* result, sspine_skeleton skeleton, const char * name) {
    *result = sspine_bone_by_name(skeleton, name);
}

SPINE_EXPORT void sspine_bone_by_index_internal(sspine_bone* result, sspine_skeleton skeleton, int index) {
    *result = sspine_bone_by_index(skeleton, index);
}

SPINE_EXPORT void sspine_get_bone_info_internal(sspine_bone_info* result, sspine_bone bone) {
    *result = sspine_get_bone_info(bone);
}

SPINE_EXPORT void sspine_get_bone_transform_internal(sspine_bone_transform* result, sspine_instance instance, sspine_bone bone) {
    *result = sspine_get_bone_transform(instance, bone);
}

SPINE_EXPORT void sspine_get_bone_position_internal(sspine_vec2* result, sspine_instance instance, sspine_bone bone) {
    *result = sspine_get_bone_position(instance, bone);
}

SPINE_EXPORT void sspine_get_bone_scale_internal(sspine_vec2* result, sspine_instance instance, sspine_bone bone) {
    *result = sspine_get_bone_scale(instance, bone);
}

SPINE_EXPORT void sspine_get_bone_shear_internal(sspine_vec2* result, sspine_instance instance, sspine_bone bone) {
    *result = sspine_get_bone_shear(instance, bone);
}

SPINE_EXPORT void sspine_get_bone_world_position_internal(sspine_vec2* result, sspine_instance instance, sspine_bone bone) {
    *result = sspine_get_bone_world_position(instance, bone);
}

SPINE_EXPORT void sspine_bone_local_to_world_internal(sspine_vec2* result, sspine_instance instance, sspine_bone bone, sspine_vec2 local_pos) {
    *result = sspine_bone_local_to_world(instance, bone, local_pos);
}

SPINE_EXPORT void sspine_bone_world_to_local_internal(sspine_vec2* result, sspine_instance instance, sspine_bone bone, sspine_vec2 world_pos) {
    *result = sspine_bone_world_to_local(instance, bone, world_pos);
}

SPINE_EXPORT void sspine_slot_by_name_internal(sspine_slot* result, sspine_skeleton skeleton, const char * name) {
    *result = sspine_slot_by_name(skeleton, name);
}

SPINE_EXPORT void sspine_slot_by_index_internal(sspine_slot* result, sspine_skeleton skeleton, int index) {
    *result = sspine_slot_by_index(skeleton, index);
}

SPINE_EXPORT void sspine_get_slot_info_internal(sspine_slot_info* result, sspine_slot slot) {
    *result = sspine_get_slot_info(slot);
}

SPINE_EXPORT void sspine_event_by_name_internal(sspine_event* result, sspine_skeleton skeleton, const char * name) {
    *result = sspine_event_by_name(skeleton, name);
}

SPINE_EXPORT void sspine_event_by_index_internal(sspine_event* result, sspine_skeleton skeleton, int index) {
    *result = sspine_event_by_index(skeleton, index);
}

SPINE_EXPORT void sspine_get_event_info_internal(sspine_event_info* result, sspine_event event) {
    *result = sspine_get_event_info(event);
}

SPINE_EXPORT void sspine_iktarget_by_name_internal(sspine_iktarget* result, sspine_skeleton skeleton, const char * name) {
    *result = sspine_iktarget_by_name(skeleton, name);
}

SPINE_EXPORT void sspine_iktarget_by_index_internal(sspine_iktarget* result, sspine_skeleton skeleton, int index) {
    *result = sspine_iktarget_by_index(skeleton, index);
}

SPINE_EXPORT void sspine_get_iktarget_info_internal(sspine_iktarget_info* result, sspine_iktarget iktarget) {
    *result = sspine_get_iktarget_info(iktarget);
}

SPINE_EXPORT void sspine_skin_by_name_internal(sspine_skin* result, sspine_skeleton skeleton, const char * name) {
    *result = sspine_skin_by_name(skeleton, name);
}

SPINE_EXPORT void sspine_skin_by_index_internal(sspine_skin* result, sspine_skeleton skeleton, int index) {
    *result = sspine_skin_by_index(skeleton, index);
}

SPINE_EXPORT void sspine_get_skin_info_internal(sspine_skin_info* result, sspine_skin skin) {
    *result = sspine_get_skin_info(skin);
}

#endif // SPINE_C_CSHARP_INTERNAL_WRAPPERS_H
